### ISSUE TITLE
Add tags to Thrive repositories

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive-Organization#1]
Should we add tags to our repositories like some popular repositories do? Like this one: https://github.com/nlohmann/json

**Comment by NickTheNick** [comment]
Yeah sure, is this for other people on GitHub searching for our repos, or people within our organization searching for them?

**Comment by hhyyrylainen** [comment]
It's for github's search (and maybe google also notices them)

**Comment by NickTheNick** [comment]
Yeah that's a good idea

**Comment by NickTheNick** [comment]
Done, added Thrive for now.

**Comment by hhyyrylainen** [comment]
Thrive as a topic is enough for this repo but the main repo should have tags like game, simulation, evolution etc.

**Comment by NickTheNick** [comment]
Ah ok gotcha. What do you think of Thrive, Game, Ogre, Simulation, and Evolution as the topics?

**Comment by hhyyrylainen** [comment]
I think those should be fine, but someone should look at other open source games on github and see if there are any tags that also apply to thrive. And maybe microbe(s)?

**Comment by NickTheNick** [comment]
For now I added strategy, biology, sandbox, c-plus-plus, and science as topics as well. We can leave the issue open though so that we can add more topics when we think of them. I'll unassign the issue from the upcoming milestone
