### ISSUE TITLE
Update GDD to reflect recent design decisions

### ISSUE THREAD

**Issue by Oliveriver** [Revolutionary-Games/Thrive-Organization#15]
Related to this thread: http://forum.revolutionarygamesstudio.com/t/microbe-stage-gdd/77

The [GDD](http://thrivegame.wikidot.com/microbe-stage-gdd) on our Wiki has become a bit stale, since many of the features outlined in it have since been revised or dropped. Updating it to reflect these new ideas will be a mammoth task but (if we keep it up to date from then on) a worthwhile one.

However, keep in mind that the GDD should be as self-coherent as possible. That means any changes to one section may affect other sections, and those should be edited accordingly. This task will require people to scan through almost every dev forum thread since the GDD was made and find the most recent consensus on each feature.

Had we started this organisation a few weeks earlier I would have had time to work on this myself. As it stands I doubt I can get much of it done before I go off to university, where I have to assume I'll have little free time. It may be that multiple people can work on this.

**Comment by NickTheNick** [comment]
I could definitely start work on this today. I can assign myself for now and if anyone else can help assign yourself and let me know.

**Comment by NickTheNick** [comment]
Finally complete! All that is left is some cleaning up of the articles that I can do later tonight and tomorrow.

**Comment by Oliveriver** [comment]
This issue also referred to the subsidiary pages (progression, visuals, etc.) which we're still yet to update. Updating the design decisions is still being discussed [here](http://forum.revolutionarygamesstudio.com/t/questions-from-the-wiki/385/11) so I don't think we can call this issue done. Hence I'm reopening it.

**Comment by hhyyrylainen** [comment]
There's been enough overhauls to the GDD and wiki updates to consider this done since 2017.
