### ISSUE TITLE
Update FAQ and About sections of Dev Forum

### ISSUE THREAD

**Issue by NickTheNick-zz** [Revolutionary-Games/Thrive-Organization#16]
It appears like the dev forums have a new feature for FAQ and About linked at the top of the page. We could use this feature to fill it in with the FAQ and About we currently have as threads.

**Comment by hhyyrylainen** [comment]
The FAQ already linked to our website. I couldn't find any way to really put extra info to the about section but I slightly increased the info in the single sentence forum summary which shows on the about page.
