### ISSUE TITLE
Move all the pages to the new wiki

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive-Organization#26]
We have a new wiki here: https://wiki.revolutionarygamesstudio.com/wiki/Main_Page

I've set it to say the license is the same as the old one and that content is copied from there, that should cover us for copy-pasting the content.

Everyone with an account on the dev forums can login there.

Old wiki: http://thrivegame.wikidot.com/home

The wiki markup syntax is different so it needs a bit of work to get it converted (and even more if you can't view the page source on the old wiki).

Much of the content should also be marked with the `{{Outdated}}` template.

**Comment by Kasterisk** [comment]
#33

**Comment by hhyyrylainen** [comment]
Most of the pages should now be done so I'll close this to mark some progress on this.
