### ISSUE TITLE
Update Microbe Stage GDD with new information and layout

### ISSUE THREAD

**Issue by NickTheNick** [Revolutionary-Games/Thrive-Organization#3]
Basically, a rewrite of the GDD to breakdown the content into more pages and link them up to pages like Getting Started. I should be able to finish this up within a week.

**Comment by crodnu** [comment]
Also getting more information on the microbe and multicellular stages would be good.

**Comment by NickTheNick** [comment]
Yeah good point, I'll work on that as well.

**Comment by NickTheNick** [comment]
Alright, the wiki is finally structured in a cohesive way, we just need to work on filling out pages now. 

In case anyone is interested I've been doing snippets of this on and off for almost half a year now so this is very satisfying to complete!
