### ISSUE TITLE
Copy over all the wiki pages to the new wiki

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive-Organization#33]
old wiki: http://thrivegame.wikidot.com/
new wiki: https://wiki.revolutionarygamesstudio.com/wiki/Main_Page
I set the new wiki license to be the same so the text can be just copy pasted.

**Comment by hhyyrylainen** [comment]
Here's a fun little page that lists pages that have links to them but don't exist: https://wiki.revolutionarygamesstudio.com/wiki/Special:WantedPages

**Comment by Kasterisk** [comment]
I have basically started working on this.

**Comment by hhyyrylainen** [comment]
Duplicate of: https://github.com/Revolutionary-Games/Thrive-Organization/issues/26
