### ISSUE TITLE
Contact old members

### ISSUE THREAD

**Issue by NickTheNick** [Revolutionary-Games/Thrive-Organization#4]
As mentioned in this thread: http://forum.revolutionarygamesstudio.com/t/release-0-4-0-thread/378

We should go through and try contacting old members of the team who haven't been active for a while. Be careful though not to contact ones who've already been emailed a few times before, we don't want to spam them. 

The link to the doc with all the emails is on Slack.

**Comment by hhyyrylainen** [comment]
I see no point in keeping this issue open.
