### ISSUE TITLE
Write Devblog outlining engine changes/thought process

### ISSUE THREAD

**Issue by Oliveriver** [Revolutionary-Games/Thrive-Organization#7]
I suggested this in Slack a while ago and think it's a worthy addition to the issues list here.

Since our previous Devblog was published all the way back in June, it's about time for another. Most of the workload since has been engine-related, so in my opinion our next Devblog should cover that. A lot of work was put into UE4 and then was scrapped. From the outside this appears like nothing; we need to tell people how we tried it and why we scrapped it. Same with Godot.

@hhyyrylainen You're closest to the engine side of things. Could you have a go at writing something up? It can be passed to the outreach people later for polishing and adding an introduction, but I doubt anyone but you could give a good explanation for what's happened.

**Comment by hhyyrylainen** [comment]
I'm writing one now

**Comment by hhyyrylainen** [comment]
posted it on slack @Oliveriver

**Comment by Oliveriver** [comment]
I've finished editing it. I'll post the draft in Slack, and if everyone's happy, we can publish today.

**Comment by Oliveriver** [comment]
Done and published: http://revolutionarygamesstudio.com/devblog-13-engine-dilemma/
