### ISSUE TITLE
Regular social media updates

### ISSUE THREAD

**Issue by NickTheNick** [Revolutionary-Games/Thrive-Organization#8]
We have a few social media sites we've neglected lately. We ought to post some updates to them soon and make sure to keep them in the loop of our activity so they don't look dead. The ones I know of so far that need these updates are:

- Twitter
- Steam
- Facebook
- Reddit 

Secondly, in the long term, we should set some system so that we can ensure regular updates to social media. I'm thinking either a way of automating posts from one site to post to other sites, or creating a calendar and assigning people to post updates on scheduled dates of each month.

**Comment by NickTheNick** [comment]
Partially addressed with the start of the new Mini Updates series. I'd wait though before considering this issue closed because we still need to address other content we'd want to post to social media.

**Comment by hhyyrylainen** [comment]
We've been doing more regular updates now.
