### ISSUE TITLE
Update wiki page on compounds

### ISSUE THREAD

**Issue by NickTheNick** [Revolutionary-Games/Thrive-Organization#9]
We have new compounds and processes that we can add to the wiki page here: http://thrivegame.wikidot.com/compound-system

**Comment by crodnu** [comment]
Here's a thing that could go in the wiki about the current process system implementation http://forum.revolutionarygamesstudio.com/t/process-system/309/9

**Comment by NickTheNick** [comment]
Ah awesome! I'll make sure to add that in.

**Comment by NickTheNick** [comment]
Done.

**Comment by crodnu** [comment]
You forgot the process system implementation :/

**Comment by NickTheNick** [comment]
Oh right thanks for reminding me. I'll add that in soon.

**Comment by NickTheNick** [comment]
Done, with info from crodnu's handy pdf and the Microbe Stage/Gameplay pages.
